{
  "contest": 367,
  "handle": "ubl4nk",
  "risk": "2",
  "title": "Malicious user can DoS the VaultManagerV2#withdraw",
  "issueId": 61,
  "issueUrl": "https://github.com/code-423n4/2024-04-dyad-findings/issues/61"
}